RED 1561135263
> greeting@1.0.0 test /home/sapagat/sandbox/greeting
> jasmine --reporter=jasmine-console-reporter

Executing 5 defined specs...
Running in random order... (seed: 94921)

Test Suites & Specs:

1. Setup
   ✔ is working (2ms)

2. Greeting
   ✔ shouts when the name is in uppercase (<1ms)
   ✔ says hello to the given name (<1ms)
   ✔ says hello with an appellative when no name given (<1ms)
   ✖ allows to greet two names in one greeting (1 failure) (1ms)

>> Done!

Failed Specs:

1. Greeting : allows to greet two names in one greeting
   TypeError: name.toUpperCase is not a function
       at <Jasmine>
       at isInUppercase /home/sapagat/sandbox/greeting/spec/greetingSpec.js:55:15
       at greet /home/sapagat/sandbox/greeting/spec/greetingSpec.js:30:7
       at UserContext.it /home/sapagat/sandbox/greeting/spec/greetingSpec.js:21:20
       at <Jasmine>
       at runCallback timers.js:705:18

Summary:

❌  Failed
Suites:  2 of 2
Specs:   5 of 5
Expects: 5 (1 failure)
Finished in 0.01 seconds