RED 1561130109
> greeting@1.0.0 test /home/sapagat/sandbox/greeting
> jasmine --reporter=jasmine-console-reporter

Executing 2 defined specs...
Running in random order... (seed: 76823)

Test Suites & Specs:

1. Greeting
   ✖ says hello to the given name (1 failure) (1ms)

2. Setup
   ✔ is working (1ms)

>> Done!

Failed Specs:

1. Greeting : says hello to the given name
   ReferenceError: greet is not defined
       at <Jasmine>
       at UserContext.it /home/sapagat/sandbox/greeting/spec/greetingSpec.js:4:5
       at <Jasmine>
       at runCallback timers.js:705:18
       at tryOnImmediate timers.js:676:5
       at processImmediate timers.js:658:5

Summary:

❌  Failed
Suites:  2 of 2
Specs:   2 of 2
Expects: 2 (1 failure)
Finished in 0.01 seconds